### ISSUE TITLE
Route [login] not defined.

### ISSUE THREAD

**Issue by MrFallen** [ilzrv/laravel-steam-auth#3]
Добрый день, получаю такую ошибку. Делаю всё по инструкции. Laravel 8.

`Route [login] not defined.`

**Comment by ilzrv** [comment]
@MrFallen можете предоставить больше данных, последовательность действий для повторения ошибки? Я перепроверил на новом Laravel 8, все работает.

**Comment by MrFallen** [comment]
Я затупил. Нужно было просто указать имя роуту. Решил данный вопрос через минуту после того как написал его сюда.
