### ISSUE TITLE
Not working at all... ofc

### ISSUE THREAD

**Issue by UndercoverNL** [ilzrv/laravel-steam-auth#5]
I don't know what you think you are doing here, but this will never work. You are making a view which should handle the response of steam with the data? That is not how things work.  You create a view which returns. And you set the redirect URL to your handle function which handles the data provided by steam. Highly not recommend using this since it will simply not work at all. This was just 1 example of tons which are not working.

You should instead use this https://github.com/invisnik/laravel-steam-auth which does work, also on laravel 8 and which does handle the responses like it should be done

**Comment by ilzrv** [comment]
@UndercoverNL At the time of validation, the package makes a request to https://steamcommunity.com/openid/login where all parameters are checked. If the validation fails, the user is redirected to the Steam login page. After successfully logging in to Steam, you get back to where validation is successful and the SteamData object is filled in.

This package has been working for several years, the examples are working and have been tested on clean versions of Laravel.

**Comment by UndercoverNL** [comment]
@ilzrv I needed to change over 50% of the controller code with actually working code from the link I posted in my original message. You are redirecting to steam in the same function as where you get the data, which is inpossible

`        if (!$this->steamAuth->validate()) {
        return $this->steamAuth->redirect();
    }`

$this->steamAuth->validate() will always return false since 

`<!--StartFragment-->        return $this-&gt;request-&gt;has('openid_assoc_handle')            &amp;&amp; $this-&gt;request-&gt;has('openid_signed')            &amp;&amp; $this-&gt;request-&gt;has('openid_sig');<!--EndFragment-->`

Will always return false to. Since this info is a response by steam, and you are retrieving this info AFTER you retrieved and validated the info in

```
        $data = $this->steamAuth->getUserData();

        if (is_null($data)) {
            return $this->steamAuth->redirect();
        }
```
that is not going to work

**Comment by ilzrv** [comment]
@UndercoverNL Most likely, a null check is not required, because the data has already been received:
```
if (is_null($data)) {
    return $this->steamAuth->redirect();
}
```

I've logged every step for you (code from readme):

```php
public function login()
{
    info(__METHOD__);

    if (!$this->steamAuth->validate()) {
        info(__METHOD__ . ' User not logged');
        return $this->steamAuth->redirect();
    }

    info(__METHOD__ . ' User logged in');

    $data = $this->steamAuth->getUserData();

    if (is_null($data)) {
        info(__METHOD__ . ' User data is null');
        return $this->steamAuth->redirect();
    }

    info(__METHOD__ . ' User name: ' . $data->getPersonaName());
    info('Redirecting to ' . $this->redirectTo);
}
```

Now let's look at the logs:

```
# 1: Go to /login
local.INFO: App\Http\Controllers\Auth\SteamAuthController::login
local.INFO: App\Http\Controllers\Auth\SteamAuthController::login User not logged
# 2: Steam will redirect you to /login (after a successful login)
local.INFO: App\Http\Controllers\Auth\SteamAuthController::login
local.INFO: App\Http\Controllers\Auth\SteamAuthController::login User logged in
local.INFO: App\Http\Controllers\Auth\SteamAuthController::login User name: IL
local.INFO: Redirecting to /home
```

**Comment by UndercoverNL** [comment]
@ilzrv I did already fixed it my self, that is not the problem, after 5 hours of custom modifications. But I am just trying to tell you that when someone is using the exact code from the controller / routes you used in the read me it will not work at all. The request will get stuck at the first if

```
    if (!$this->steamAuth->validate()) {
        return $this->steamAuth->redirect();
    }
```

It will return you to the HOME router with no further action. What you want is make a GET request with only `return $this->steamAuth->redirect();` inside the function. And as redirect link another get request named handle for example. On handle, you can retrieve the steam data. You have to use at least 2 functions.

**Comment by ilzrv** [comment]
@UndercoverNL

`$this->steamAuth->validate()` returns only true or false
`$this->steamAuth->redirect()` redirects you to the Steam login page

What's your problem? 

I rechecked with a new Laravel installation.  Everything works fine.

1. Did you publish the configuration file? 
2. Did you add API keys?

**Comment by UndercoverNL** [comment]
@ilzrv 

1. yes
2. yes

My problem is that `$this->steamAuth->validate()` always returns false

**Comment by ilzrv** [comment]
@UndercoverNL `validate` always returns false on direct login, should be true only when there is a redirect from Steam.

**Comment by UndercoverNL** [comment]
@ilzrv So you are redirecting back to the same route as where the user came from? And then validate should return true?

**Comment by ilzrv** [comment]
@UndercoverNL When you successfully log in on the Steam and click "Sign In". Then the redirect will take place to the same page but with additional parameters that will be used for checking.

**Comment by UndercoverNL** [comment]
@ilzrv mm, strange way of doing it, maybe define that a bit better in the read me, since the "redirect URL" needs to be the same URL as your login page. 

Also, it is not using your config but the config from pterodactyl/config. Which need to be created and setup by hand

**Comment by ilzrv** [comment]
@UndercoverNL

The configuration has a description: https://github.com/ilzrv/laravel-steam-auth/blob/12b3743500b2a991b323515ba1f0d00e9c462475/config/steam-auth.php#L5-L15

The request specifies the redirect url: https://github.com/ilzrv/laravel-steam-auth/blob/12b3743500b2a991b323515ba1f0d00e9c462475/src/SteamAuth.php#L223-L225

Everything works out of the box. If you have any suggestions, please make a pull request.

**Comment by UndercoverNL** [comment]
@ilzrv laravel-steam-auth/config/steam-auth.php isn't used. config() is using the pterodactyl/config

**Comment by ilzrv** [comment]
@UndercoverNL This was tested on pure Laravel. I can't be responsible for third-party libraries.

**Comment by UndercoverNL** [comment]
@ilzrv I am on pure Laravel...
